### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by VinayarajVR** [yarl/pattypan#115]
I have been using Pattypan for so long, and its a fantastic tool, looks like tailormade for me. Today I am not able to login to the program. Constantly prompts "login failed". Please help.

I can login to Wikimedia Commons site with same password.
Then I tried to enable two factor authentication, still I can not login to Pattypan.
Please help me resolve it at the earliest as it is very important.

Vinayaraj

**Comment by lirazelf** [comment]
Hey there, just to add that one of our partners (National Library of Scotland using WikiSource as a from-home work option during COVID lockdown period) is experiencing the same issue - they tried to log in here but GitHub is being weird for them so just c&p-ing their text on their behalf: 

“I uploaded files using Pattypan to Wiki Commons on Friday 3rd April but on Monday 7th and Tuesday 8th got a ‘log in failed’ message after spreadsheet generation and check. Same issue as reported earlier. I also had an issue on Friday 3rd April where the upload started and then stopped partway through. Please look at this asap as we can’t add content and we have people working from home on this.”

**Comment by Hansmuller2** [comment]
I have the same problem the last few hours: upon trying to login, i get a message in Dutch to the tune of login failed. Never have seen this before using this wonderful tool Pattypan! Please turn Pattypan on again! Thanks, hansmuller2

**Comment by yarl** [comment]
It looks this https://github.com/michal-josef-spacek/vicuna/commit/c4640dda4ad8b99bd88d38547afc9d7e27c3ccbd should fix issue, I will do PR unless someone will be quicker.

**Comment by Hansmuller2** [comment]
Dear Yarl, Thank you so much for getting Pattypan back to work!

**Comment by VinayarajVR** [comment]
Dear Yarl
Thanks a Ton. These quarantine days are apt for uploading, thanks again

**Comment by chillg123** [comment]
> It looks this [michal-josef-spacek/vicuna@c4640dd](https://github.com/michal-josef-spacek/vicuna/commit/c4640dda4ad8b99bd88d38547afc9d7e27c3ccbd) should fix issue, I will do PR unless someone will be quicker.

Dear Yarl, 

Thank you for this fix. I'm an IT admin working on helping our library staff members with this. I've updated the source code and rezipped the file. How would I go about getting Pattypan to run as a .jar again after performing the edits. ?

**Comment by yarl** [comment]
Hey all, I've just pushed fixed version. Please download and check: https://github.com/yarl/pattypan/releases/

**Comment by Hansmuller2** [comment]
Still: login failed. I'm sorry, just now both the new Pattypan20.04 and the previous version I used Pattypan19.06 refuse to permit login: login failed. This is strange, because this afternoon Pattypan19.06 let me login and upload. I hope it can be fixed anyway, thanks!

**Comment by Hansmuller2** [comment]
Tried again and again: now Pattypan20.04 works! Thanks!

**Comment by MuseoCollections** [comment]
Hello, I am also experiencing this problem and I am unable to log in. I can login to wikimedia with my credential but when I try to use these credentials to complete upload via Pattypan, it says login failed. I am using Pattypan20.04, I have cleared my cache,  but I am still getting failed log in. Any suggestions would be much appreciated.

**Comment by Ophidienne** [comment]
Hello there, same problem here. Loggin in to wikimedia is no problem, but the login with pattypan fails. I'm also using pattypan20.04. Has there been any development? Thanks in advance!

**Comment by VinayarajVR** [comment]
Will this problem be fixed in near future?

**Comment by VinayarajVR** [comment]
Please today when I tried to login, even though the password is correct, the login is failed, please attend

**Comment by VinayarajVR** [comment]
Now it works
